[daemon]

[inputs]

    [inputs.zmq]
    topology = "pubsub"
    endpoint = "tcp://*:2120"

[filters]

[outputs]

    [outputs.s3]
    access_key = ""
    secret_key = ""
    region = "ap-northeast-1"
    bucket = "mylogs"
    codec = "msgpack"
    key_prefix = "sample"
    flush_interval = 30  # in seconds
    max_queue_length = 10000

