[daemon]

[inputs]

    [inputs.zmq]
    topology = "pubsub"
    endpoint = "tcp://*:2120"

[filters]

[outputs]

    [outputs.s3]
    access_key = ""
    secret_key = ""
    bucket = "mylogs"
    codec = "msgpack"
    flush_interval = 30  # in seconds
    max_queue_length = 10000

